package com.myspace.bpmproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Age")
	private java.lang.Integer age;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;

	public person() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public person(java.lang.Integer age, java.lang.String name) {
		this.age = age;
		this.name = name;
	}

}